// <auto-generated />
namespace spsServerAPI.Database.spsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class tutorEmailAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tutorEmailAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201502202336397_tutorEmailAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
