// <auto-generated />
namespace spsServerAPI.Database.spsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class PlacedTableIntroduced : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlacedTableIntroduced));
        
        string IMigrationMetadata.Id
        {
            get { return "201502221755504_PlacedTableIntroduced"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
