// <auto-generated />
namespace spsServerAPI.Database.spsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddProgrammeStageYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProgrammeStageYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201501291221015_AddProgrammeStageYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
